export const LOGIN = 'AUTH_ACTION::LOGIN';
export const LOGOUT = 'AUTH_ACTION::LOGOUT';
export const REGISTRATION = 'AUTH_ACTION::REGISTRATION';
export const REGISTRATION_MANAGER = 'AUTH_ACTION::REGISTRATION_MANAGER';
