export const GET_ALL_HOTELS = 'HOTELS_ACTION::GET_ALL_HOTELS';
export const GET_HOTEL = 'HOTELS_ACTION::GET_HOTEL';
export const GET_ALL_HOTEL_ROOMS = 'HOTELS_ACTION::GET_ALL_HOTEL_ROOMS';
export const ORDER_ROOM = 'HOTELS_ACTION::ORDER_ROOM';
